### ISSUE TITLE
Confusing syntax

### ISSUE THREAD

**Issue by parafoxia** [Jonxslays/Starr#1]
https://github.com/Jonxslays/Starr/blob/54fc755e053a731434ab49bacf49d2d51c573a62/starr/bot.py#L81-L83

According to PEP 8's section on [When to Use Trailing Commas](https://www.python.org/dev/peps/pep-0008/#when-to-use-trailing-commas), tuples defined in this manner should be wrapped in brackets, and not simply have a trailing comma after the variable name. The syntax is confusing otherwise.

Bot looks pretty sick though ngl, so good job so far!

**Comment by Jonxslays** [comment]
Valid point. There's a lot of cleaning up to do still.
