### ISSUE TITLE
Consider using alternative for blocking read of sql files

### ISSUE THREAD

**Issue by thomm-o** [Jonxslays/Starr#38]
https://github.com/Jonxslays/Starr/blob/013c26b4dadea68c2cb1161b51d35fa2427a206b/starr/db.py#L136

Consider using `aiofiles` or similar alternative to read sql files to prevent unnecessarily blocking the bot.

**Comment by Jonxslays** [comment]
this function is only ever called on bot startup. 
right now it would really just be another dependency.
